#!/usr/bin/env python3

import argparse, re, os, re
from markdown import markdown
from markdown.extensions.codehilite import CodeHiliteExtension

sep = ','
errRegExp = re.compile(r'"err"')
commentRegExp = re.compile(r'^(\s*)#', re.MULTILINE)

def get_text(lines, is_md):
    text = os.linesep.join(lines).strip()

    if is_md:
        text = markdown(
            text,
            output_format='html5',
            extensions=['fenced_code', CodeHiliteExtension(linenums=True, guess_lang=False)]
        )

    return commentRegExp.sub('\\1&num;', text)

def write_markdown(question, answer, p2, tag, tags, fout, is_md):
    res = question and answer
    data = [question, answer]

    if p2:
        data.append(p2)

    if res:
        text = sep.join('"'
            + get_text(lines, is_md).replace('"', '""')
            + '"' for lines in data
        )

        if is_md and errRegExp.search(text):
            print('Markdown error (wrong syntax): ' + text)

        fout.write(text + (sep + '"' + ' '.join(tags | tag) + '"' if (tags | tag) else '') + os.linesep)

    return res

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Parse markdown into Anki TSV')
    parser.add_argument('file', metavar='<file-name>', type=str, help='name of a file to parse')
    parser.add_argument('--tags', metavar='<tags1,tag2,...>', help='comma separated tags list')
    parser.add_argument('--no-markdown', action='store_true', help='do not produce markdown')

    tags = set()
    if parser.parse_args().tags:
        tags = set(map(str.strip, parser.parse_args().tags.split(',')))

    is_md = not parser.parse_args().no_markdown

    with open(parser.parse_args().file, 'r') as fin:
        fout = open('./anki.tsv', 'w')

        num = 0
        question = []
        answer = []
        p2 = []
        tag = set()
        code_started = None

        for line in fin:
            line = line.rstrip()

            if line == '####----####':
                break

            if not line and not answer:
                continue

            if line.startswith('```'):
                code_started = not code_started

            if line.startswith('---') and not code_started:
                res = write_markdown(question, answer, p2, tag, tags, fout, is_md)

                if num > 0 and not res and not tag:
                    raise Exception('No data', question, answer, p2, tag, tags, is_md)

                if res or num <= 0:
                    num += 1

                question = []
                answer = []
                p2 = []

                continue


            if line.lstrip().startswith('# ') and not question:
                matches = re.search(r'\[\s*([-,\s\w]+)\s*\]\s*`?\s*$', line)

                if matches:
                    tag = set(map(str.strip, matches.group(1).split(',')))

            elif num > 0:
                if line.lstrip().startswith('>'):
                    line = re.sub(r'\s*>(?:\s{1})?', '', line)

                    if answer:
                        p2.append(line)

                    else:
                        question.append(line)

                else:
                    answer.append(line)

        write_markdown(question, answer, p2, tag, tags, fout, is_md)
        fout.close()

        # last divider, empty note
        if not question:
            num -= 1

        print('Notes created: ', num)
